spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState
